[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.riscv64gc-unknown-linux-musl]
rustflags = ["-C", "linker=riscv64-linux-musl-cc", "-C", "target-feature=-crt-static"]
